### PR TITLE
Fixed filter and pagination the list of requests and workflows

### PR DESCRIPTION
**Pull request by lgalis**
Fixed the filter and the pagination for the list of requests and workflows.
Fixed spacing around the Approval title.

Filter workflows:
Screenshot from 2020-01-15 16-07-40

Filter requests:
Screenshot from 2020-01-15 16-06-38

Pagination:
Screenshot from 2020-01-15 16-14-29

Placeholders for the requests/workflows table:
Screenshot from 2020-01-17 08-24-25

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@lgalis I think that the filter input and pagination buttons should be hidden when the request is fired.

Right now if you are writing longer filter string, it will cut you off in the middle.

**Comment by Hyperkid123** [comment]
Also, the request does not seem to be debounced. So you create an API call on each keypress. This will resolve in inconsistent results because the calls are not resolved in sequential order.

**Comment by lgalis** [comment]
> Also, the request does not seem to be debounced. So you create an API call on each keypress. This will resolve in inconsistent results because the calls are not resolved in sequential order.

@Hyperkid123 - thank you - I see the same issue in the filter for the Platforms and tabs - I will fix those as well.

**Comment by lgalis** [comment]
@Hyperkid123  - feedback addressed

**Comment by Hyperkid123** [comment]
@lgalis the debouce is now working properly. 

The filter toolbar is still disappearing though when the request is fired. It should stay there and only the table should be replaced by the placeholder.

Also, there are no empty states, but I think that can be done later.

**Comment by lgalis** [comment]
@Hyperkid123 - updated the placeholders. The Empty states will be added in a separate PR.

**Pull request merged**
