### PR TITLE
Update pf4 versions

### PR DESCRIPTION
**Pull request by Hyperkid123**
follow up of #293 from @lgalis 

Added a single commit that updates the FCE dependencies to stable versions and uses latest PF stable release (fixed a couple of issues. Namely snapshots and wizard layout).

### CODE REVIEW

**Comment by rvsia** [comment]
On ci beta I still see the old styles mixed with the one ones.. but not sure why it happens :-/

Screenshot from 2020-07-01 17-20-36
Screenshot from 2020-07-01 17-18-01

**Comment by Hyperkid123** [comment]
:thinking: i shall try the production version. Maybe it's just an issue with the dev bundle. Approval uses different css loading than catalog and sources.

**Comment by rvsia** [comment]
Yeah, I am thinking the same - in the past, we encountered the issue where prod version did not load all CSS (and locally it was ok). So, the css loading could take some enhancement.

**Comment by Hyperkid123** [comment]
@rvsia @eclarizio so the issue with the overflowing table. That is a PF bug and its cause when one of the table cells contains a very long string. I don't know how much we can do about that other than reporting it as an issue. Realistically, this is something that won't happen very often.

Here is a screen from their docs:
screenshot-www patternfly org-2020 07 01-17_57_25


The border around a wizard is a tough one. We have the same CSS, same CSS values, and order as in PF docs. I think this might be an issue on the chrome side but, we don't have these issues in catalog our sources. 

The CSS loading is the same as it is in sources I don't think there is anything to update.

**Comment by Hyperkid123** [comment]
I believe that we are dealing with outdated chrome styles. I will look into it but I don't think we can fix it on our side.

**Comment by Hyperkid123** [comment]
@eclarizio we can't take care of these kinds of issues. That markup will be always similar. We should maybe turn it off for react files.

**Comment by eclarizio** [comment]
@Hyperkid123 That's fine if there's a valid reason, I just wasn't sure how difficult or how feasible it was to refactor whatever codeclimate is complaining about for this PR. It looks like it's just complaining about a small duplication, so I'll merge as-is and we can address if need be later, but ultimately I think it's very minor and getting this in is more important.

**Comment by Hyperkid123** [comment]
@rvsia @eclarizio just to follow up. The wizard styles are OK once deployed. We were dealing with an incorrect order of CSS assets loading while running it locally.

**Pull request merged**
