### PR TITLE
Fix icon spacing on Request Transcript screen

### PR DESCRIPTION
**Pull request by epwinchell**
Spacing between icons and text was inconsistant.

Jira: https://projects.engineering.redhat.com/browse/SSP-1627

Old
Screen Shot 2020-07-07 at 4 14 11 PM

New
Screen Shot 2020-07-07 at 4 12 09 PM

### CODE REVIEW

**Comment by epwinchell** [comment]
@miq-bot add_reviewer @lgalis 
@miq-bot add_label bug

**Comment by epwinchell** [comment]
@dippy-bot add_reviewer @lgalis 
@dippy-bot  add_label bug

**Comment by epwinchell** [comment]
@eclarizio Looks like @dippy-bot isn't working here

**Comment by eclarizio** [comment]
@epwinchell Yeah, looks like he got stuck and errored out, will restart it.

**Pull request merged**
