### PR TITLE
Lazy load data when expanding row of a request

### PR DESCRIPTION
**Pull request by rvsia**
Fixes https://projects.engineering.redhat.com/browse/SSP-1140

Extended row of a request is now lazy loaded - it is loaded only after a user expand its row.

+ Also added tests for changed components

approval

@Hyperkid123

### CODE REVIEW

**Comment by rvsia** [comment]
The same issue is present in the Workflows table, where all groups are loaded at the same time. @Hyperkid123

**Comment by Hyperkid123** [comment]
@rvsia can you do the workflow table aswell?

**Comment by rvsia** [comment]
> @rvsia can you do the workflow table aswell?

Working on it. Should I add it here or make a separate PR?

**Comment by Hyperkid123** [comment]
@rvsia separate, please. I will create a new ticket too.

**Pull request merged**
